name: Terraform CI

on:
  pull_request: {}
  push:
    branches:
        - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "latest"
          terraform_wrapper: true

      # Terraform Format Check (fails CI if formatting is off)
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init -input=false

      # Validate Terraform
      - name: Terraform Validate
        run: terraform validate

      # Optional: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -input=false